### PR TITLE
URL decode `Role` `AssumeRolePolicyDocument`

### PR DESCRIPTION
**Pull request by RedbackThomson**
Description of changes:
The response from creating or reading a `Role` encodes the `AssumeRolePolicyDocument` with URL encoding (any non-alphanumeric character is converted to hex). When attempting to update the role with the encoded string, the API returns an error. This pull request adds hook code to convert it back into a multiline string so that it matches the original spec.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vijtrip2** [comment]
Looks good... 
* Should the existing test resource be changed to include multiline policy?
* Why not add similar hook for update-role ?

**Review by A-Hilaly — APPROVED** [review]
This looks good!

**Review by jaypipes — CHANGES_REQUESTED** [review]
Technically, would be good to have an sdk_update_post_set_output.go.tpl file that does the same thing as the create code path added here...

**Comment by RedbackThomson** [comment]
> Technically, would be good to have an sdk_update_post_set_output.go.tpl file that does the same thing as the create code path added here...

Update doesn't return the policy document as far as I can see (https://docs.aws.amazon.com/sdk-for-go/api/service/iam/#UpdateRoleOutput). But there are a few update methods in the IAM controller.

**Pull request merged**
