### PR TITLE
remove dev preview from olm file in preparation for GA

### PR DESCRIPTION
**Pull request by acornett21**
Issue #, if available:
N/A
Description of changes:
Removing dev preview to prepare for GA.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
Signed-off-by: Adam D. Cornett <adc@redhat.com>

### CODE REVIEW

**Comment by acornett21** [comment]
@jaypipes Did you mention that there would be other CRD/Kinds for this controller? If so I can hold off on this PR until those are in place and also add in the new `Kinds`.

**Comment by jaypipes** [comment]
> @jaypipes Did you mention that there would be other CRD/Kinds for this controller? If so I can hold off on this PR until those are in place and also add in the new `Kinds`.

Yes @acornett21 I need to get the `User` and `Group` resources done for the IAM controller.

**Comment by acornett21** [comment]
@jaypipes I added the missing CRD's. This should be GTG now.

**Review by jaypipes — APPROVED** [review]
:+1:

**Pull request merged**
